### ISSUE TITLE
Error while running TrainingAnomalyDetector_public.py

### ISSUE THREAD

**Issue by Peggy118** [ekosman/AnomalyDetectionCVPR2018-Pytorch#129] opened 2022-07-13 15:56 UTC
Hi. @ekosman  Thanks for your fantastic work.

I tried the Feature extraction and it seemed to work well, but when I used pre-computed features, getting the below error when running TrainingAnomalyDetector_public.py, and the program was broken.

`(adCVPR18) root@WIN-47D7BGGOVAB:/home/galaxy/anaconda3/envs/adCVPR18/AnomalyDetectionCVPR2018-Pytorch# python TrainingAnomalyDetector_public.py --features_path "/home/galaxy/anaconda3/envs/adCVPR18/AnomalyDetectionCVPR2018-Pytorch/features/c3d" --annotation_path "/home/galaxy/anaconda3/envs/adCVPR18/AnomalyDetectionCVPR2018-Pytorch/Train_Annotation.txt"
2022-07-13 16:38:32,308 Training for 2 epochs
2022-07-13 16:38:32,472 VideoIter:: ERROR!! (Force using another index:
15967)
Feature doesn't exist: `/home/galaxy/anaconda3/envs/adCVPR18/AnomalyDetectionCVPR2018-Pytorch/features/c3d/**Training_Normal_Videos_Anomaly/Normal_Videos920_x264.txt**`
2022-07-13 16:38:32,822 VideoIter:: ERROR!! (Force using another index:
1151)

Command : `python TrainingAnomalyDetector_public.py --features_path "features/c3d" --annotation_path "Train_Annotation.txt"`

`/home/galaxy/anaconda3/envs/adCVPR18/AnomalyDetectionCVPR2018-Pytorch/` is the entire directionary.

I searched the issues and found 2 similar problems [#95](https://github.com/ekosman/AnomalyDetectionCVPR2018-Pytorch/issues/95) and [#8](https://github.com/ekosman/AnomalyDetectionCVPR2018-Pytorch/issues/8), but there is no solution for this problem. I think my feature path is right... It contains all files downloaded from the ReadMe link, just like below. 

![image](https://user-images.githubusercontent.com/92985997/178776656-4d419126-e08a-4d0d-b072-84baa2b5af40.png)

Btw, I checked the content of all pre-computed features and there is no feature of "**Normal_Videos920_x264.txt**" (for example), which is listed in the Train_Annotation.txt. Do I misuse command?

Sorry for bothering you. I am truly new to python and deep learning. Any suggestion that might help is appreciated. Thank you.

Entire error:
![image](https://user-images.githubusercontent.com/92985997/178775502-26ca62d2-abc0-4014-82fa-f5ade848e8fb.png)

**Comment by Chuttyboy** [comment] 2022-07-16 02:14
@Peggy118 

I also have the same problem did you resolve your issues?

**Comment by ekosman** [comment] 2022-07-16 09:45
@Chuttyboy @Peggy118 
I think the problem is that the dropbox contains two zip files for the normal videos, e.g. `Training-Normal-Videos-Part-1.zip` and `Training-Normal-Videos-Part-2.zip`. However, the annotations use a different naming: `Training-Normal-Videos-Anomaly`.

Could you try merging the two aforementioned directories into one called `Training-Normal-Videos-Anomaly`? If that helps, I may propose to create a script that organize the dataset automatically after downloading.

**Comment by Peggy118** [comment] 2022-07-16 10:46
> @Chuttyboy @Peggy118 I think the problem is that the dropbox contains two zip files for the normal videos, e.g. `Training-Normal-Videos-Part-1.zip` and `Training-Normal-Videos-Part-2.zip`. However, the annotations use a different naming: `Training-Normal-Videos-Anomaly`.
> 
> Could you try merging the two aforementioned directories into one called `Training-Normal-Videos-Anomaly`? If that helps, I may propose to create a script that organizes the dataset automatically after downloading.

@ekosman 
Thanks for your kind reply. Do you mean that the original video dataset from the author Chen has the 2 zip files? I used the pre-computed features from this link(https://drive.google.com/drive/folders/1rhOuAdUqyJU4hXIhToUnh5XVvYjQiN50?usp=sharing) and there is a directory named `Training_Normal_Videos_Anomaly` containing some features in txt files, for example, `Normal_Videos007_x264.txt.` 

Also, I found that in the existing `Train_Annotation.txt` there are some videos that do not exist in the pre-computed C3D features. I think this might be the reason, but I cannot figure out all the missing videos according to the annotations file... Am I supposed to create a new file containing all annotations corresponding to the pre-computed features to do the training?

Thanks in advance. Apologise if I misunderstand the suggestion. 



@Chuttyboy 
Sorry I didn't. Neither do I know how to prepare the Train_Annotation.txt. I just used the one that has already existed in this project.

**Comment by ekosman** [comment] 2022-07-16 11:31
@Peggy118 
Ah I see. I'm aware that a few videos don't have the corresponding features in this drive. Probably because they are too short. How many such warnings do you get? Does the training continue after this?

**Comment by Peggy118** [comment] 2022-07-16 11:38
@ekosman 
Too many I guess. It just repeats the warnings for different videos again and again, and I think the training does not start at all...

**Comment by ekosman** [comment] 2022-07-16 11:40
@Peggy118 
I'll try to reproduce it. Thanks for reporting!

**Comment by Chuttyboy** [comment] 2022-07-19 04:25
@ekosman  

Unable to download the dataset from the given dropbox link.  I got this error while downloading normal Training videos


![Annotation 2022-07-19 093432](https://user-images.githubusercontent.com/79959547/179664420-da690472-5800-40d3-88b5-5ebad74f7d28.png)

Thanks

**Comment by ekosman** [comment] 2022-07-21 20:08
> @ekosman Too many I guess. It just repeats the warnings for different videos again and again, and I think the training does not start at all...

Hi, I finally got to it. However, it seems that the problem does not reproduce on my PC:
![תמונה](https://user-images.githubusercontent.com/10260165/180306050-421c7f24-16a9-4834-adf1-0ec92fc52341.png)

**Comment by ekosman** [comment] 2022-07-21 20:10
> @ekosman
> 
> Unable to download the dataset from the given dropbox link. I got this error while downloading normal Training videos
> 
> ![Annotation 2022-07-19 093432](https://user-images.githubusercontent.com/79959547/179664420-da690472-5800-40d3-88b5-5ebad74f7d28.png)
> 
> Thanks

Hi. I just tried to download it too from the dropbox link, but sadly found that it is broken :(
I will try to restore the videos somehow. I don't remember if I have the dataset stored anywhere. If I do, I will try to upload it.

**Comment by ekosman** [comment] 2022-07-28 11:05
@Peggy118 As I wasn't able to reproduce the problem, I wonder whether this is still relevant? If yes, please let me know. Otherwise I'll close the issue by 31/7.

**Comment by ekosman** [comment] 2022-08-04 08:46
Closed as this is not reproducible.

**Closed by ekosman** 2022-08-04 08:46 UTC
Labels: bug, help wanted
