### ISSUE TITLE
about data read

### ISSUE THREAD

**Issue by libb999** [ekosman/AnomalyDetectionCVPR2018-Pytorch#12] opened 2019-12-31 08:07 UTC
thank you for your project.
when i run feature_extractor.py,i get a error:
TypeError: 'set' object does not support indexing

i  already downloads UCF video data in '--dataset_path', c3d.pickle in '--pretrained_3d',
'--annotation_path' and '--annotation_path_test' default in your project named Train_Annotation.txt and Test_Annotation.txt

**Comment by PHDPeter** [comment] 2020-01-15 10:27
see a solution here (https://github.com/ekosman/AnomalyDetectionCVPR2018-Pytorch/issues/13), you need to just remove the set function from the return of vid_list

**Comment by libb999** [comment] 2020-01-16 02:32
> see a solution here (#13), you need to just remove the set function from the return of vid_list

thank you very much!,but when i remove set(),i get a new error:
![123](https://user-images.githubusercontent.com/38545551/72488269-7089c080-384b-11ea-84f8-f1734835837c.png)

**Comment by PHDPeter** [comment] 2020-01-16 09:34
I this looks like a new error unrelated to the first, maybe start a new issue and I have no good ideas for this problem and you can layout all the input/system set up you have with this problem.

**Comment by PHDPeter** [comment] 2020-01-16 13:03
they seem to be having the same problem here (https://github.com/ekosman/AnomalyDetectionCVPR2018-Pytorch/issues/1) so that might help

**Comment by ekosman** [comment] 2020-01-30 10:34
Duplicate of #13

**Closed** 2020-01-30 10:34 UTC
Labels: duplicate, help wanted

**Comment by ChunmianLin** [comment] 2020-08-19 01:23
> thank you for your project.
> when i run feature_extractor.py,i get a error:
> TypeError: 'set' object does not support indexing
> 
> i already downloads UCF video data in '--dataset_path', c3d.pickle in '--pretrained_3d',
> '--annotation_path' and '--annotation_path_test' default in your project named Train_Annotation.txt and Test_Annotation.txt

Hi, could you please provide me the UCF dataset? I cannot obtain the normal data due to the unknown corruption.

**Comment by PHDPeter** [comment] 2020-08-19 09:07
The feature extracted data is in the README file if you need it but you can fix the set error you have thereby just removing the "set" part from it, detailed in this issue I think.
Hope that helps.
